FROM mysql:latest

MAINTAINER Richard Raumberger <richard.raumberger@edu.fh-joanneum.at>
LABEL Customizes the base mysql image by adding the database scripts and providing deployment script.

ADD customization /docker-entrypoint-initdb.d/