#create user table

CREATE TABLE IF NOT EXISTS user
(
  id         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  mail       VARCHAR(32)  NOT NULL,
  password   VARCHAR(32)  NOT NULL,
  salt       VARCHAR(512) NOT NULL,
  `created`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
  ENGINE = INNODB;

#create news table

CREATE TABLE IF NOT EXISTS news
(
  id         BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title      VARCHAR(256)  NOT NULL,
  message    VARCHAR(1024) NOT NULL,
  author     BIGINT /* NOT NULL REFERENCES person (id)*/, /* TODO uncomment when person table is introduced*/
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
  ENGINE = INNODB;