# select correct database
USE pse;

DROP TABLE IF EXISTS hobby;
DROP TABLE IF EXISTS knowledge;
DROP TABLE IF EXISTS mailaddress;
DROP TABLE IF EXISTS phonenumber;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS person_image;
DROP TABLE IF EXISTS person_status;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS community;
DROP TABLE IF EXISTS community_user;
